// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package manager

import (
	"go-dora-api/api/manager"
)

type ControllerV1 struct{}

func NewV1() manager.IManagerV1 {
	return &ControllerV1{}
}
