// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-dora-api/internal/dao/internal"
)

// internalDictionaryDao is an internal type for wrapping the internal DAO implementation.
type internalDictionaryDao = *internal.DictionaryDao

// dictionaryDao is the data access object for the table dictionary.
// You can define custom methods on it to extend its functionality as needed.
type dictionaryDao struct {
	internalDictionaryDao
}

var (
	// Dictionary is a globally accessible object for table dictionary operations.
	Dictionary = dictionaryDao{
		internal.NewDictionaryDao(),
	}
)

// Add your custom methods and functionality below.
