// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-dora-api/internal/dao/internal"
)

// internalManageDao is an internal type for wrapping the internal DAO implementation.
type internalManageDao = *internal.ManageDao

// manageDao is the data access object for the table manage.
// You can define custom methods on it to extend its functionality as needed.
type manageDao struct {
	internalManageDao
}

var (
	// Manage is a globally accessible object for table manage operations.
	Manage = manageDao{
		internal.NewManageDao(),
	}
)

// Add your custom methods and functionality below.
