// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-dora-api/internal/dao/internal"
)

// internalMediaDao is an internal type for wrapping the internal DAO implementation.
type internalMediaDao = *internal.MediaDao

// mediaDao is the data access object for the table media.
// You can define custom methods on it to extend its functionality as needed.
type mediaDao struct {
	internalMediaDao
}

var (
	// Media is a globally accessible object for table media operations.
	Media = mediaDao{
		internal.NewMediaDao(),
	}
)

// Add your custom methods and functionality below.
