// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-dora-api/internal/dao/internal"
)

// internalSysManagerRoleDao is an internal type for wrapping the internal DAO implementation.
type internalSysManagerRoleDao = *internal.SysManagerRoleDao

// sysManagerRoleDao is the data access object for the table sys_manager_role.
// You can define custom methods on it to extend its functionality as needed.
type sysManagerRoleDao struct {
	internalSysManagerRoleDao
}

var (
	// SysManagerRole is a globally accessible object for table sys_manager_role operations.
	SysManagerRole = sysManagerRoleDao{
		internal.NewSysManagerRoleDao(),
	}
)

// Add your custom methods and functionality below.
